### PR TITLE
Add a basic unit test for the Windows version of the rename

### PR DESCRIPTION
**Pull request by gatesvp**
This should resolve issue #1

### CODE REVIEW

**Comment by jbenet** [comment]
LGTM. 

@gatesvp this may work on unix and other platforms too. may want to just make it general (build everywhere)

**Comment by gatesvp** [comment]
So I actually _just_ tested that on Linux box and it turns out that it doesn't matter :)

Because the root file `rename_windows.go` is Windows-only, the test file `rename_windows_test.go` is simply ignored.

**Comment by jbenet** [comment]
oh I meant that I think the test will work on unix too-- that it seems cross platform so maybe run it on Linux too (ie name it rename_test.go so it runs everywhere)

**Comment by jbenet** [comment]
i'll fix it

**Comment by jbenet** [comment]
3ac97f6

**Comment by gatesvp** [comment]
Got it, thank you :)

On Tue, Apr 28, 2015 at 12:51 AM, Juan Batiz-Benet <notifications@github.com

**Pull request merged**
